#!/usr/bin/env bash
# upstream_sync.sh — sync ittalenthireca-sketch/Spinr with upstream srikumarimuddana-lab/spinrvm
#
# Usage:
#   ./scripts/upstream_sync.sh [--dry-run] [--auto-merge]
#
#   --dry-run     Fetch + diff only; no branch creation or commits
#   --auto-merge  After CI passes, merge the sync PR automatically
#                 (requires GH_AUTO_MERGE=true env var as a safety gate)
#
# Run order that makes sense:
#   1. Fetch upstream
#   2. Diff — report new commits and changed files
#   3. Create dated branch  sync/upstream-YYYY-MM-DD
#   4. Merge upstream/main --no-commit
#   5. Restore files that contain P0 production fixes (see PROTECTED_FILES)
#   6. Apply ruff auto-fixes + sort imports
#   7. Commit + push
#   8. Open PR with summary report
#
# Manual trigger (from repo root):
#   bash scripts/upstream_sync.sh
#
# Automated trigger: see .github/workflows/upstream-sync.yml (twice daily)
#
set -euo pipefail

# ── Config ──────────────────────────────────────────────────────────────────
UPSTREAM_REMOTE="upstream"
UPSTREAM_URL="https://github.com/srikumarimuddana-lab/spinrvm.git"
FORK_REMOTE="origin"
BASE_BRANCH="main"
REPORT_FILE="docs/sync-reports/$(date +%Y-%m-%d)-upstream-sync.md"

# Files where OUR version must always win over upstream.
# Add to this list whenever a P0 production fix diverges from upstream.
PROTECTED_FILES=(
  "backend/routes/webhooks.py"        # async worker pattern — P0
  "fly.toml"                          # app+worker process split — P0
  "backend/Dockerfile"                # multi-stage build + security patches
)

DRY_RUN=false
AUTO_MERGE=false
for arg in "$@"; do
  case $arg in
    --dry-run)    DRY_RUN=true ;;
    --auto-merge) AUTO_MERGE=true ;;
  esac
done

BRANCH="sync/upstream-$(date +%Y-%m-%d)"

# ── Helpers ──────────────────────────────────────────────────────────────────
log()  { echo "[sync] $*"; }
warn() { echo "[sync] WARN: $*" >&2; }
die()  { echo "[sync] ERROR: $*" >&2; exit 1; }

require_clean_working_tree() {
  if ! git diff --quiet HEAD; then
    die "Working tree is dirty. Commit or stash changes before running sync."
  fi
}

# ── Step 0: Preflight ────────────────────────────────────────────────────────
log "Preflight checks..."
require_clean_working_tree
git fetch "$FORK_REMOTE" "$BASE_BRANCH" --quiet
git checkout "$BASE_BRANCH" --quiet
git pull "$FORK_REMOTE" "$BASE_BRANCH" --quiet

# ── Step 1: Fetch upstream ────────────────────────────────────────────────────
log "Fetching upstream ($UPSTREAM_URL)..."
if ! git remote get-url "$UPSTREAM_REMOTE" &>/dev/null; then
  git remote add "$UPSTREAM_REMOTE" "$UPSTREAM_URL"
fi
git fetch "$UPSTREAM_REMOTE" main --quiet

# ── Step 2: Diff report ───────────────────────────────────────────────────────
NEW_COMMITS=$(git log --oneline "$BASE_BRANCH".."$UPSTREAM_REMOTE/main" 2>/dev/null || echo "")
NEW_COMMIT_COUNT=$(echo "$NEW_COMMITS" | grep -c . || true)
CHANGED_FILES=$(git diff --name-only "$BASE_BRANCH" "$UPSTREAM_REMOTE/main" 2>/dev/null || echo "")
CHANGED_FILE_COUNT=$(echo "$CHANGED_FILES" | grep -c . || true)

log "Upstream delta: $NEW_COMMIT_COUNT new commits, $NEW_COMMIT_COUNT file changes"

if [ "$NEW_COMMIT_COUNT" -eq 0 ]; then
  log "Already in sync with upstream. Nothing to do."
  mkdir -p "$(dirname "$REPORT_FILE")"
  cat > "$REPORT_FILE" <<REPORT
# Upstream Sync Report — $(date +%Y-%m-%d)

**Status:** Already in sync — no new upstream commits.

Generated by \`scripts/upstream_sync.sh\` at $(date -u +"%Y-%m-%dT%H:%M:%SZ").
REPORT
  echo "$REPORT_FILE"
  exit 0
fi

if [ "$DRY_RUN" = true ]; then
  log "[DRY RUN] Would create branch: $BRANCH"
  log "[DRY RUN] New commits:"
  echo "$NEW_COMMITS" | head -20
  log "[DRY RUN] Changed files:"
  echo "$CHANGED_FILES" | head -30
  exit 0
fi

# ── Step 3: Create sync branch ────────────────────────────────────────────────
log "Creating branch $BRANCH..."
if git show-ref --quiet "refs/heads/$BRANCH"; then
  warn "Branch $BRANCH already exists; checking it out."
  git checkout "$BRANCH"
else
  git checkout -b "$BRANCH"
fi

# ── Step 4: Merge upstream --no-commit ────────────────────────────────────────
log "Merging upstream/main (--no-commit --no-ff)..."
if ! git merge --no-commit --no-ff "$UPSTREAM_REMOTE/main" 2>&1; then
  # Merge conflicts — try to auto-resolve protected files
  warn "Merge conflicts detected. Restoring protected files from ORIG_HEAD..."
  for f in "${PROTECTED_FILES[@]}"; do
    if git ls-files --error-unmatch "$f" &>/dev/null 2>&1; then
      git checkout ORIG_HEAD -- "$f" 2>/dev/null && log "  Protected: $f (kept ours)"
    fi
  done
  # Check if any conflicts remain
  REMAINING=$(git diff --name-only --diff-filter=U 2>/dev/null || echo "")
  if [ -n "$REMAINING" ]; then
    die "Unresolved conflicts remain in:\n$REMAINING\nResolve manually and re-run, or use --dry-run to inspect."
  fi
fi

# ── Step 5: Restore protected files ──────────────────────────────────────────
log "Restoring protected files (P0 production fixes)..."
for f in "${PROTECTED_FILES[@]}"; do
  if git show ORIG_HEAD:"$f" &>/dev/null 2>&1; then
    git checkout ORIG_HEAD -- "$f"
    log "  Kept ours: $f"
  fi
done

# ── Step 6: Lint auto-fix (backend only) ─────────────────────────────────────
if command -v python &>/dev/null && [ -f backend/pyproject.toml ] || [ -f backend/.ruff.toml ] || [ -f pyproject.toml ]; then
  log "Running ruff auto-fix..."
  (cd backend && python -m ruff check . --fix --quiet 2>/dev/null) || true
  git add backend/ 2>/dev/null || true
fi

# ── Step 7: Commit ────────────────────────────────────────────────────────────
log "Committing sync..."
git add -A
if git diff --cached --quiet; then
  log "No staged changes after merge. Possibly all changes were in protected files."
else
  git commit -m "chore(sync): merge upstream changes $(date +%Y-%m-%d)

$NEW_COMMIT_COUNT commits from srikumarimuddana-lab/spinrvm merged.
Protected files kept from our fork: ${PROTECTED_FILES[*]}"
fi

# ── Step 8: Push + PR ─────────────────────────────────────────────────────────
log "Pushing $BRANCH..."
git push -u "$FORK_REMOTE" "$BRANCH"

# Build PR body
COMMITS_SECTION=$(echo "$NEW_COMMITS" | head -20 | sed 's/^/- /')
FILES_SECTION=$(echo "$CHANGED_FILES" | head -30 | sed 's/^/- /')
PROTECTED_SECTION=$(printf '- %s\n' "${PROTECTED_FILES[@]}")

PR_URL=$(gh pr create \
  --title "chore(sync): upstream merge $(date +%Y-%m-%d) ($NEW_COMMIT_COUNT commits)" \
  --base "$BASE_BRANCH" \
  --body "## Upstream Sync — $(date +%Y-%m-%d)

**$NEW_COMMIT_COUNT** new upstream commits merged from \`srikumarimuddana-lab/spinrvm\`.

### New upstream commits
$COMMITS_SECTION

### Changed files ($CHANGED_FILE_COUNT)
$FILES_SECTION

### Protected files (our P0 fixes preserved)
$PROTECTED_SECTION

## Test plan
- [ ] \`backend-test\` passes (ruff + pytest)
- [ ] \`frontend-test\` passes
- [ ] \`rider-app-test\` passes
- [ ] \`driver-app-test\` passes
- [ ] No P0 functionality regressed (webhooks async worker, process split)

---
*Generated by \`scripts/upstream_sync.sh\` — $(date -u +"%Y-%m-%dT%H:%M:%SZ")*" 2>&1)

log "PR created: $PR_URL"

# ── Step 9: Write report ──────────────────────────────────────────────────────
mkdir -p "$(dirname "$REPORT_FILE")"
cat > "$REPORT_FILE" <<REPORT
# Upstream Sync Report — $(date +%Y-%m-%d)

**Status:** Sync PR opened — awaiting CI
**PR:** $PR_URL
**Branch:** $BRANCH
**Upstream commits merged:** $NEW_COMMIT_COUNT
**Files changed:** $CHANGED_FILE_COUNT

## New upstream commits
$COMMITS_SECTION

## Changed files
$FILES_SECTION

## Protected files (our overrides)
$PROTECTED_SECTION

## Next steps
1. Wait for CI to pass on the PR above
2. Review any protected-file conflicts flagged in the PR body
3. Merge the PR (squash merge preferred)
4. Run this script again in ~12h for the next scheduled sync

Generated by \`scripts/upstream_sync.sh\` at $(date -u +"%Y-%m-%dT%H:%M:%SZ").
REPORT

log "Report written to $REPORT_FILE"
log "Done. PR: $PR_URL"
